// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBddLzZzkIq4zKMgege8kM39CRqZ2QRKV4',
    appId: '1:74018677524:web:f7a4882ca10bd2ef18d801',
    messagingSenderId: '74018677524',
    projectId: 'sns-flut',
    authDomain: 'sns-flut.firebaseapp.com',
    storageBucket: 'sns-flut.appspot.com',
    measurementId: 'G-VQFXPCWHRJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFGSZy1VlpHbBFXkXOlz6TTbHU1ekrxwE',
    appId: '1:74018677524:android:10c2a645627ce7a818d801',
    messagingSenderId: '74018677524',
    projectId: 'sns-flut',
    storageBucket: 'sns-flut.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB5mbRPj36_BLiGSkmXiZfcNSumJMYMv4',
    appId: '1:74018677524:ios:b1d6dcf65901552918d801',
    messagingSenderId: '74018677524',
    projectId: 'sns-flut',
    storageBucket: 'sns-flut.appspot.com',
    iosClientId: '74018677524-6e8c5j087d72jm33kq71s3tia9m9el1e.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSns',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB5mbRPj36_BLiGSkmXiZfcNSumJMYMv4',
    appId: '1:74018677524:ios:b1d6dcf65901552918d801',
    messagingSenderId: '74018677524',
    projectId: 'sns-flut',
    storageBucket: 'sns-flut.appspot.com',
    iosClientId: '74018677524-6e8c5j087d72jm33kq71s3tia9m9el1e.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSns',
  );
}
